#!/usr/bin/env python3
"""Run record_separation_node and run_record_separation_node in isolation.

Usage:
    python test_record_separation.py <pdf_path>

Finds template.json by walking up from the PDF's directory.
Outputs go to <base_folder>/record_test/:
    ocr.csv
    record_separation.py   (generated by codex)
    record_separation.json (output of the script)
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys

import pdfplumber

sys.path.insert(0, os.path.dirname(__file__))

from src.agents.record_separation import record_separation_node, run_record_separation_node


def _find_base_folder(start: str) -> str:
    current = os.path.abspath(start)
    while True:
        if os.path.isfile(os.path.join(current, "template.json")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            raise SystemExit(f"Error: could not find template.json above {start}")
        current = parent


def _extract_ocr(pdf_path: str, out_path: str) -> None:
    fields = ["id", "page", "x0", "top", "x1", "bottom", "text"]
    with pdfplumber.open(pdf_path) as pdf, \
         open(out_path, "w", newline="", encoding="utf-8", errors="replace") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        word_id = 0
        for page_num, page in enumerate(pdf.pages, start=1):
            for word in (page.extract_words() or []):
                writer.writerow({
                    "id": word_id, "page": page_num,
                    "x0": word["x0"], "top": word["top"],
                    "x1": word["x1"], "bottom": word["bottom"],
                    "text": word["text"],
                })
                word_id += 1


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Test record_separation_node and run_record_separation_node."
    )
    parser.add_argument("pdf_path", help="Path to the PDF to process.")
    args = parser.parse_args()

    pdf_path    = os.path.abspath(args.pdf_path)
    base_folder = _find_base_folder(os.path.dirname(pdf_path))
    record_test = os.path.join(base_folder, "record_test")
    ocr_path    = os.path.join(record_test, "ocr.csv")

    os.makedirs(record_test, exist_ok=True)

    if not os.path.isfile(pdf_path):
        print(f"Error: PDF not found at {pdf_path}", file=sys.stderr)
        sys.exit(1)

    template_path = os.path.join(base_folder, "template.json")
    if not os.path.isfile(template_path):
        print(f"Error: template.json not found at {template_path}", file=sys.stderr)
        sys.exit(1)

    with open(template_path, encoding="utf-8") as f:
        template = json.load(f).get("template", [])

    print("Extracting OCR...")
    _extract_ocr(pdf_path, ocr_path)
    print(f"  OCR saved → {ocr_path}")

    # pdf_path dirname must be record_test so the generated script lands there
    state = {
        "pdf_path":     os.path.join(record_test, os.path.basename(pdf_path)),
        "ocr_csv_path": ocr_path,
        "template":     template,
        "cost":         [],
    }

    print("\n── record_separation_node ───────────────────────────────────")
    result = record_separation_node(state)
    state["cost"] += result.get("cost", [])
    print(f"duration: {result['cost'][0]['duration_s']}s")

    print("\n── run_record_separation_node ───────────────────────────────")
    result = run_record_separation_node(state)
    state["cost"] += result.get("cost", [])
    print(f"duration: {result['cost'][0]['duration_s']}s")

    output = os.path.join(record_test, "record_separation.json")
    if os.path.isfile(output):
        with open(output, encoding="utf-8") as f:
            data = json.load(f)
        print(f"\n{len(data.get('records', []))} record(s) found → {output}")
    else:
        print(f"Warning: {output} was not created.", file=sys.stderr)


if __name__ == "__main__":
    main()
