from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
import time
from typing import Any

from src.models.codex import codex_silent
from src.prompts.block_separation_prompt import PROMPT_BLOCK_SEPARATION


# ── animated display ──────────────────────────────────────────────────────────

_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
_GREEN_TICK = "\033[32m✓\033[0m"


def _spinner(label: str, stop_event: threading.Event, result: dict) -> None:
    frame = 0
    sys.stdout.write("\n")
    sys.stdout.flush()
    while not stop_event.is_set():
        sys.stdout.write(f"\r\033[K  {label}  {_FRAMES[frame % len(_FRAMES)]}")
        sys.stdout.flush()
        frame += 1
        time.sleep(0.1)
    tok = result.get("tokens")
    suffix = f"  {_GREEN_TICK}  {tok:,} tokens" if tok is not None else f"  {_GREEN_TICK}"
    sys.stdout.write(f"\r\033[K  {label}{suffix}\n")
    sys.stdout.flush()


def run_block_separation_node(state: dict[str, Any]) -> dict[str, Any]:
    """Execute the block_separation.py script generated by block_separation_node.

    Reads:
        state["pdf_path"]     – used to derive the train directory
        state["ocr_csv_path"] – OCR CSV path passed as first arg to the script

    Side-effect:
        Runs block_separation.py, which writes block_separation.json into train_dir.
    """
    train_dir   = os.path.dirname(state["pdf_path"])
    script_path = os.path.join(train_dir, "block_separation.py")
    ocr_csv     = state["ocr_csv_path"]

    t0 = time.time()
    result = subprocess.run(
        [sys.executable, script_path, ocr_csv, train_dir],
        capture_output=True,
        text=True,
    )
    duration = time.time() - t0

    if result.returncode != 0:
        raise RuntimeError(
            f"block_separation.py failed (exit {result.returncode}):\n{result.stderr}"
        )
    if result.stdout:
        print(result.stdout, end="")

    return {"cost": [{"phase": "run_block_separation", "duration_s": round(duration, 3)}]}


def block_separation_node(state: dict[str, Any]) -> dict[str, Any]:
    """Ask codex to write a block-separation script tailored to the inferred template.

    Reads:
        state["template"]       – list of template node dicts from template_inference.
        state["ocr_csv_path"]   – path to the full OCR CSV.
        state["agent_space"]    – working directory where codex will write the script.

    Writes:
        Nothing new to state; side-effect is the script written inside agent_space.
    """
    template_json = json.dumps(state["template"], indent=2)
    ocr_csv_path = state["ocr_csv_path"]
    train_dir = os.path.dirname(state["pdf_path"])

    prompt = PROMPT_BLOCK_SEPARATION(ocr_csv_path, template_json)

    stop_event = threading.Event()
    spinner_result: dict = {}
    spinner_thread = threading.Thread(
        target=_spinner,
        args=("block_separation", stop_event, spinner_result),
        daemon=True,
    )
    spinner_thread.start()

    t0 = time.time()
    returncode, tokens = codex_silent(prompt, train_dir, task="block_separation")
    duration = time.time() - t0

    spinner_result["tokens"] = tokens if returncode == 0 else None
    stop_event.set()
    spinner_thread.join(timeout=0.5)

    if returncode != 0:
        raise RuntimeError(f"codex failed for block_separation (exit code {returncode})")

    cost_entry: dict = {"phase": "block_separation", "duration_s": round(duration, 3)}
    if tokens is not None:
        cost_entry["tokens"] = tokens

    return {"cost": [cost_entry]}
