from __future__ import annotations

import json
import os
import shutil
import time
from typing import Any

# src/pipeline.py sits one level above this file (src/agents/)
_PIPELINE_SRC = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "pipeline.py")


def collect_extraction_scripts_node(state: dict[str, Any]) -> dict[str, Any]:
    """Assemble the self-contained pipeline folder.

    1. Collect every .py file generated by Codex from block_samples/<id>/ into
       train_dir/extraction_scripts/.
    2. Create train_dir/pipeline/.
    3. Move extraction_scripts/ into pipeline/.
    4. Move block_separation.py from train_dir into pipeline/.
    5. Move record_separation.py from train_dir into pipeline/.
    6. Copy src/pipeline.py into pipeline/.

    Reads:
        state["agent_space"]  – working directory for this document
    """
    t0 = time.time()
    agent_space = state["agent_space"]
    train_dir   = os.path.dirname(state["pdf_path"])

    block_samples_dir      = os.path.join(train_dir, "block_samples")
    extraction_scripts_dir = os.path.join(train_dir, "extraction_scripts")
    pipeline_dir           = os.path.join(train_dir, "pipeline")

    # ── 1. collect extraction scripts ────────────────────────────────────────
    # Codex writes <template_id>.py into its CWD (block_samples/<id>/); move each
    # .py file found there into extraction_scripts/.
    os.makedirs(extraction_scripts_dir, exist_ok=True)
    collected = []
    for template_id in sorted(os.listdir(block_samples_dir)):
        sample_dir = os.path.join(block_samples_dir, template_id)
        if not os.path.isdir(sample_dir):
            continue
        for fname in os.listdir(sample_dir):
            if not fname.endswith(".py"):
                continue
            shutil.move(
                os.path.join(sample_dir, fname),
                os.path.join(extraction_scripts_dir, fname),
            )
            collected.append(fname)

    print(f"collect_extraction_scripts: {len(collected)} extraction script(s) collected")

    # ── 2. create pipeline folder ─────────────────────────────────────────────
    os.makedirs(pipeline_dir, exist_ok=True)

    # ── 3. move extraction_scripts/ into pipeline/ ────────────────────────────
    dst_scripts = os.path.join(pipeline_dir, "extraction_scripts")
    if os.path.exists(dst_scripts):
        shutil.rmtree(dst_scripts)
    shutil.move(extraction_scripts_dir, dst_scripts)
    print(f"  extraction_scripts/ → pipeline/extraction_scripts/")

    # ── 4. move block_separation.py into pipeline/ ────────────────────────────
    block_sep_src = os.path.join(train_dir, "block_separation.py")
    if os.path.exists(block_sep_src):
        shutil.move(block_sep_src, os.path.join(pipeline_dir, "block_separation.py"))
        print(f"  block_separation.py  → pipeline/block_separation.py")
    else:
        print("  warning: block_separation.py not found in train_dir, skipping")

    # ── 5. move record_separation.py into pipeline/ ───────────────────────────
    record_sep_src = os.path.join(train_dir, "record_separation.py")
    if os.path.exists(record_sep_src):
        shutil.move(record_sep_src, os.path.join(pipeline_dir, "record_separation.py"))
        print(f"  record_separation.py → pipeline/record_separation.py")
    else:
        print("  warning: record_separation.py not found in train_dir, skipping")

    # ── 7. copy src/pipeline.py into pipeline/ ────────────────────────────────
    shutil.copy2(_PIPELINE_SRC, os.path.join(pipeline_dir, "pipeline.py"))
    print(f"  pipeline.py          → pipeline/pipeline.py")
    print(f"collect_extraction_scripts: pipeline ready at {pipeline_dir}")

    own_entry: dict = {
        "phase": "collect_extraction_scripts",
        "duration_s": round(time.time() - t0, 3),
    }

    phases = list(state.get("cost") or []) + [own_entry]
    total_duration = round(sum(p["duration_s"] for p in phases), 3)
    total_tokens = sum(p["tokens"] for p in phases if "tokens" in p) or None

    report: dict = {"phases": phases, "total_duration_s": total_duration}
    if total_tokens is not None:
        report["total_tokens"] = total_tokens

    document_dir = os.path.dirname(agent_space)
    doc_dir = os.path.join(document_dir, "metadata")
    os.makedirs(doc_dir, exist_ok=True)

    # ── 8. move pipeline/ to the document directory ───────────────────────────
    pipeline_dst = os.path.join(document_dir, "pipeline")
    if os.path.exists(pipeline_dst):
        shutil.rmtree(pipeline_dst)
    shutil.move(pipeline_dir, pipeline_dst)
    print(f"  pipeline/            → {pipeline_dst}")

    cost_path = os.path.join(doc_dir, "cost.json")
    with open(cost_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(f"cost report → {cost_path}")

    return {"cost": [own_entry]}
