from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
import time
from typing import Any

from src.models.codex import codex_silent
from src.prompts.record_separation_prompt_2 import PROMPT_RECORD_SEPARATION


_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
_GREEN_TICK = "\033[32m✓\033[0m"


def _spinner(label: str, stop_event: threading.Event, result: dict) -> None:
    frame = 0
    sys.stdout.write("\n")
    sys.stdout.flush()
    while not stop_event.is_set():
        sys.stdout.write(f"\r\033[K  {label}  {_FRAMES[frame % len(_FRAMES)]}")
        sys.stdout.flush()
        frame += 1
        time.sleep(0.1)
    tok = result.get("tokens")
    suffix = f"  {_GREEN_TICK}  {tok:,} tokens" if tok is not None else f"  {_GREEN_TICK}"
    sys.stdout.write(f"\r\033[K  {label}{suffix}\n")
    sys.stdout.flush()


def run_record_separation_node(state: dict[str, Any]) -> dict[str, Any]:
    """Execute the record_separation.py script generated by record_separation_node.

    Reads:
        state["pdf_path"]     – used to derive the train directory
        state["ocr_csv_path"] – OCR CSV path passed as first arg to the script

    Side-effect:
        Runs record_separation.py, which writes record_separation.json into train_dir.
    """
    train_dir   = os.path.dirname(state["pdf_path"])
    script_path = os.path.join(train_dir, "record_separation.py")
    ocr_csv     = state["ocr_csv_path"]

    t0 = time.time()
    result = subprocess.run(
        [sys.executable, script_path, ocr_csv, train_dir],
        capture_output=True,
        text=True,
    )
    duration = time.time() - t0

    if result.returncode != 0:
        raise RuntimeError(
            f"record_separation.py failed (exit {result.returncode}):\n{result.stderr}"
        )
    if result.stdout:
        print(result.stdout, end="")

    return {"cost": [{"phase": "run_record_separation", "duration_s": round(duration, 3)}]}


def record_separation_node(state: dict[str, Any]) -> dict[str, Any]:
    """Ask codex to write a record-separation script tailored to the inferred template.

    A "record" is one full instance of the repeating template structure on a page.
    The generated script detects record boundaries from the vertical word distribution.

    Reads:
        state["template"]       – list of template node dicts from template_inference.
        state["ocr_csv_path"]   – path to the train OCR CSV (passed to codex for context).
        state["pdf_path"]       – used to derive train_dir (where the script is written).

    Writes:
        record_separation.py into train_dir (script not executed here).
    """
    template_json = json.dumps(state["template"], indent=2)
    ocr_csv_path  = state["ocr_csv_path"]
    train_dir     = os.path.dirname(state["pdf_path"])

    prompt = PROMPT_RECORD_SEPARATION(ocr_csv_path, template_json)

    stop_event = threading.Event()
    spinner_result: dict = {}
    spinner_thread = threading.Thread(
        target=_spinner,
        args=("record_separation", stop_event, spinner_result),
        daemon=True,
    )
    spinner_thread.start()

    t0 = time.time()
    returncode, tokens = codex_silent(prompt, train_dir, task="record_separation")
    duration = time.time() - t0

    spinner_result["tokens"] = tokens if returncode == 0 else None
    stop_event.set()
    spinner_thread.join(timeout=0.5)

    if returncode != 0:
        raise RuntimeError(f"codex failed for record_separation (exit code {returncode})")

    cost_entry: dict = {"phase": "record_separation", "duration_s": round(duration, 3)}
    if tokens is not None:
        cost_entry["tokens"] = tokens

    return {"cost": [cost_entry]}
